### ISSUE TITLE
Update Triton Runtime Server to support TensorRT 8

### ISSUE THREAD

**Issue by Phelan164** [kserve/modelmesh-serving#103]
Need to support TensorRT 8 model which run in Triton Inference Server 21.11-py3 (or above)

I tried to update Triton Inference Server image to nvcr.io/nvidia/tritonserver:21.09-py3 and got the below error.
It seem to have change in interface then could not connect to the server
![image](https://user-images.githubusercontent.com/2509508/148909045-33510e5f-e54f-48a4-a329-31d5a6ca1df8.png)

**Describe your proposed solution**

**Describe alternatives you have considered**

**Additional context**

**Comment by pvaneck** [comment]
Hmm, can't say we have much experience with using TensorRT currently. But certainly would like to make it work! What is the model file structure you are using? I _think_  the modelmesh-runtime-adapter currently expects a structure like: `s3://bucket/tensorrt/model.plan`. I am not really familiar with TensorRT, but depending on what Triton expects, the adapter may need some tweaking.

**Comment by njhill** [comment]
If any code changes are needed to support this in the adapter, they should be very minor and will be equivalent to whatever is needed for https://github.com/kserve/modelmesh-serving/issues/78.

**Comment by ckadner** [comment]
We updated Triton to version 23 https://github.com/kserve/modelmesh-serving/pull/359

Feel free to reopen if you can still reproduce this issue in the latest version of [ModelMesh-Serving v0.11.2](https://github.com/kserve/modelmesh-serving/releases/tag/v0.11.2).
