### ISSUE TITLE
Add sample Keras model to minio images

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#107]
Since ModelMesh supports deploying Keras models as noted [here](https://github.com/kserve/modelmesh-serving/blob/main/docs/model-types/keras.md), we should ensure that our minio images have a sample Keras model that users can try.

Both the FVT and quickstart image should probably be updated:
kserve/modelmesh-minio-dev-examples
kserve/modelmesh-minio-examples

**Comment by tedhtchang** [comment]
@pvaneck Image updated in my docker hub
Updated some doc here: #109

**Comment by pvaneck** [comment]
Docker images updated in KServe repository and #109 merged.
