### ISSUE TITLE
install.sh script failed with "usage: sleep seconds"

### ISSUE THREAD

**Issue by tedhtchang** [kserve/modelmesh-serving#113]
**Describe the bug**
The install.sh failed with this message on OSX 12.x but not in OSX 11.x. It seems that `sleep "10s"` syntax no long works after the latest OSX update.
```
Pods found with selector '--field-selector metadata.name=etcd' are not ready yet. Waiting 10 secs...
usage: sleep seconds
```

**To Reproduce**
Following the Quick Start guide to run a `./scripts/install.sh --namespace modelmesh-serving --quickstart` command.

**Expected behavior**
`Installing ModelMesh Serving built-in runtimes`

**Environment (please complete the following information):**

- OS: `OSX 12.1`

**Comment by pvaneck** [comment]
It's probably fine to just use `sleep 10` since the default unit of time is seconds for most implementations of the sleep util I believe.
