### ISSUE TITLE
Add ModelMetadata endpoint support

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#136]
Users may want to find the input tensor name and/or shape of a particular model. The v2 predict protocol outlines a [ModelMetadata API](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata-1). We should have ModelMesh support this as I believe Triton and MLServer already expose this endpoint.

Related issue and discussion: https://github.com/kserve/modelmesh-serving/issues/104

**Comment by njhill** [comment]
I think all that should be needed is the addition of that rpc to those advertised by the adapter logic for Triton and MLServer [here](https://github.com/kserve/modelmesh-runtime-adapter/blob/main/model-mesh-triton-adapter/server/server.go#L296) and [here](https://github.com/kserve/modelmesh-runtime-adapter/blob/main/model-mesh-mlserver-adapter/server/server.go#L560), as well as to the id extraction config set by the controller [here](https://github.com/kserve/modelmesh-serving/blob/c8f9cf129a2f231df1fb75bdc858b21d430df84d/controllers/modelmesh/cluster_config.go#L36). And test coverage of course.
