### ISSUE TITLE
Support of model pipeline

### ISSUE THREAD

**Issue by saeid93** [kserve/modelmesh-serving#161]
Does kserve modelmesh support pipelining models in consecutive steps in the form of inference graph? Some thing like similar technologies like [Seldon Inference graph](https://docs.seldon.io/projects/seldon-core/en/latest/graph/inference-graph.html), [Ray Deployment Graph](https://docs.ray.io/en/latest/serve/deployment-graph.html)?

**Comment by pvaneck** [comment]
KServe is on the cusp of supporting it once this InferenceGraph PR merges: https://github.com/kserve/kserve/pull/1910
Then with that in place, some time might be needed to ensure/validate that it works with ModelMesh deployed InferenceServices. 

So, soon this will be supported with ModelMesh as it is quite an important feature!

**Comment by saeid93** [comment]
Awesome! looking forward to trying it out soon, is there an estimate on the official release date?

**Comment by rachitchauhan43** [comment]
@saeid93 : We have KServe inferencegraphs alpha version out since 0.9.0 . Feel free to test it out and let us know what other features you intend to see. We can have those as part of the roadmap.
https://kserve.github.io/website/0.10/modelserving/inference_graph/

**Comment by haiminh2001** [comment]
> KServe is on the cusp of supporting it once this InferenceGraph PR merges: [kserve/kserve#1910](https://github.com/kserve/kserve/pull/1910) Then with that in place, some time might be needed to ensure/validate that it works with ModelMesh deployed InferenceServices.
> 
> So, soon this will be supported with ModelMesh as it is quite an important feature!

Hi, as I tested, InferenceGraph has still not worked with ModelMesh, correct me if I am wrong. Can you estimate when it will support ModelMesh or it is even in the roadmap ?
