### ISSUE TITLE
Quick start not working for Mac M1 laptops

### ISSUE THREAD

**Issue by nrnc** [kserve/modelmesh-serving#162]
**Is your feature request related to a problem? If so, please describe.**

When trying the quick start guide, model mesh controller pod and model mesh serving pod are in pending state due to node affinity rules, it has only amd64

**Describe your proposed solution**
Adding the arm64 option in the nodeSelector values will be suffice i guess

**Describe alternatives you have considered**
I tried to edit the deployments and added the arm64 option

**Additional context**

Related issue #231

**Comment by pvaneck** [comment]
Hey, thanks for trying on the M1 Macs. Right, the `arm64` entry will need to be added to the [controller config](https://github.com/kserve/modelmesh-serving/blob/main/config/manager/manager.yaml#L38). However, I'm thinking you'll also be hindered by the lack of `arm64` images being built.

I do have a branch https://github.com/pvaneck/modelmesh-serving/tree/multiarch that has this change along with references to a lot of images which were rebuilt for arm64. I was experimenting deploying ModelMesh on a Jetson Nano, and I am not sure if this ModelMesh install will also work on your Mac. Still perhaps worth trying.

In any case, it looks like it'd be useful to have multi-arch support for the images at some point.

**Comment by sriumcp** [comment]
+1 for this feature for local development on Mac apple chipset.

**Comment by ckadner** [comment]
https://github.com/kserve/modelmesh-serving/issues/231#issuecomment-1244109045
