### ISSUE TITLE
Add sample inference requests for sample models

### ISSUE THREAD

**Issue by IntelliJJ824** [kserve/modelmesh-serving#165]
**Describe the bug**
I have seen an example-models.md file indicating that there are mnist in different model types (such as Onnx mnist.onnx, Keras mnist.h5). It can be found it: `https://github.com/kserve/modelmesh-serving/blob/main/docs/example-models.md`.

However, I am wondering if there are any instructions about how to sent the inference requests to these models, since there have occurred the  following problems:
**To Reproduce**
`MODEL_NAME=kears-example`
` curl -X POST -k http://localhost:8008/v2/models/${MODEL_NAME}/infer -d '{"inputs": [{ "name": "predict", "shape": [1, 64], "datatype": "FP32", "data": [0.0, 0.0, 1.0, 11.0, 14.0, 15.0, 3.0, 0.0, 0.0, 1.0, 13.0, 16.0, 12.0, 16.0, 8.0, 0.0, 0.0, 8.0, 16.0, 4.0, 6.0, 16.0, 5.0, 0.0, 0.0, 5.0, 15.0, 11.0, 13.0, 14.0, 0.0, 0.0, 0.0, 0.0, 2.0, 12.0, 16.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.0, 16.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0, 7.0, 0.0, 0.0, 0.0, 0.0, 11.0, 13.0, 12.0, 1.0, 0.0]}]}'`

Here is the incorrect NVALID_ARGUMENT we got:
`{"code":3,"message":"inference.GRPCInferenceService/ModelInfer: INVALID_ARGUMENT: unexpected inference input 'predict' for model 'kears-example__ksp-f3ccc51d50'"}`

Can I get the guide on how to specify the input for other model types on mnist.

**Comment by pvaneck** [comment]
Hey @IntelliJJ824. I agree, we should have documentation for the format for sending inference requests for these example models. Most of the example models have sample inference requests in the end to end tests ([keras example](https://github.com/kserve/modelmesh-serving/blob/main/fvt/inference.go#L244)). I can surface these out into the docs.

Another thing that was recently added was support for the [ModelMetadata API ](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata-1). Hitting this endpoint can provided details about the expected input and output:

Ex: 
```sh
grpcurl  -plaintext   -proto fvt/proto/kfs_inference_v2.proto  -d '{ "name": "example-tensorflow-mnist"}' localhost:8033   inference.GRPCInferenceService.ModelMetadata
```
