### ISSUE TITLE
How to make inter-server connection is missing from the documentation

### ISSUE THREAD

**Issue by saeid93** [kserve/modelmesh-serving#169]
I couldn't find any guide on how to build the inter-server connection links in the inference server. Could someone please either add this or point me to link if it is already present in the doc
![0 2 0-highlevel](https://user-images.githubusercontent.com/6298780/174789912-5f25eace-46f0-4ada-aee9-ee93192dd618.png)
?

**Comment by njhill** [comment]
@saeid93 the inference servers themselves do not talk to each other, all of the inter-pod communication is "internal" and between the model-mesh containers. For mostly historical reasons, a thrift-based RPC library called "litelinks" is used for this. It was developed previously within IBM (mostly predates gRPC), and later open-sourced [here](https://github.com/IBM/litelinks-core). I hope that answers your question!

**Comment by saeid93** [comment]
@njhill Thank you for your answer, could you then please give me some information regarding how I can make the internal model-mesh container connections? Basically, I want to cascade some models output, intputs together, something like: model1 -> model2 -> model3

**Comment by njhill** [comment]
@saeid93 sorry for the delayed response. For composing models you could take a look at the [Inference Graph](https://github.com/kserve/kserve/tree/master/docs/samples/graph) functionality recently added to KServe. I'm not sure whether this has been tested with ModelMesh-based InferenceService endpoints yet but it should work in theory.

Alternatively, if you've implemented a custom model server with your own logic for inferencing, this could include "re-entrant" calls to models within the same ModelMesh cluster, i.e. having a gRPC client make calls to `localhost:<port>` where `<port>` is the configured external inferencing port exposed by the modelmesh containers (default 8033).

**Comment by saeid93** [comment]
@njhill thanks for the answer! I didn't know the inference graph feature is now out, will check it out. I'm using the Triton server and my pipelines have some external logic which I implement in separate Python scripts I should see if I can implement it using the inference graph.

**Comment by yuzisun** [comment]
> @njhill thanks for the answer! I didn't know the inference graph feature is now out, will check it out. I'm using the Triton server and my pipelines have some external logic which I implement in separate Python scripts I should see if I can implement it using the inference graph.

We are going to announce soon, the [tutorial](https://kserve.github.io/website/master/modelserving/inference_graph/image_pipeline/) is available, let us know if that fits your need!

**Comment by yuzisun** [comment]
> > @njhill thanks for the answer! I didn't know the inference graph feature is now out, will check it out. I'm using the Triton server and my pipelines have some external logic which I implement in separate Python scripts I should see if I can implement it using the inference graph.
> 
> We are going to announce soon, the [tutorial](https://kserve.github.io/website/master/modelserving/inference_graph/image_pipeline/) is available, let us know if that fits your need! I am interested in to know your external logic and if possible we can support your use case out of the box.

**Comment by saeid93** [comment]
Thanks for sending the documentation @yuzisun part. This is one specific use case that I'm not sure whether it is possible currently or not.
This is one particular use case that might already be supported but I couldn't do it following docs.
I have a set of interconnected nodes in which each of them has a number of models and I want each request to pass through a different set of models for example I want each request 1 to pass through a different set of models in each node (A possible usecase is that I have requests with different latency-accuracy requirements and I want to choose the path of the request based on that). Is this possible in the current implementation?
![multi-model](https://user-images.githubusercontent.com/6298780/181790732-dcbab48e-2658-426c-a409-a7fdf5a119e9.png)
