### ISSUE TITLE
Message: inference.GRPCInferenceService/ModelInfer: INVALID_ARGUMENT: unexpected inference input 'predict' for model 'example-mnist-predictor__ksp-c3597b719f'

### ISSUE THREAD

**Issue by xauthulei** [kserve/modelmesh-serving#18]
Try to update the model type(using tensorflow instead of sklearn) and location following[ the example ](https://github.com/xauthulei/modelmesh-serving/blob/main/docs/predictors/README.md), will get this error:

```
 % grpcurl \
  -plaintext \
  -proto fvt/proto/kfs_inference_v2.proto \
  -d '{ "model_name": "example-mnist-predictor", "inputs": [{ "name": "predict", "shape": [1, 64], "datatype": "FP32", "contents": { "fp32_contents": [0.0, 0.0, 1.0, 11.0, 14.0, 15.0, 3.0, 0.0, 0.0, 1.0, 13.0, 16.0, 12.0, 16.0, 8.0, 0.0, 0.0, 8.0, 16.0, 4.0, 6.0, 16.0, 5.0, 0.0, 0.0, 5.0, 15.0, 11.0, 13.0, 14.0, 0.0, 0.0, 0.0, 0.0, 2.0, 12.0, 16.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.0, 16.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0, 7.0, 0.0, 0.0, 0.0, 0.0, 11.0, 13.0, 12.0, 1.0, 0.0] }}]}' \
  localhost:8033 \
  inference.GRPCInferenceService.ModelInfer
ERROR:
  Code: InvalidArgument
  Message: inference.GRPCInferenceService/ModelInfer: INVALID_ARGUMENT: unexpected inference input 'predict' for model 'example-mnist-predictor__ksp-c3597b719f'
```

**Comment by tedhtchang** [comment]
@xauthulei Based on the example here https://github.com/kserve/modelmesh-serving/blob/beef10ae025d4cf12a98016e13a68c2381505c78/fvt/predictor_test.go#L416-L418

The request should be:
```
grpcurl -plaintext -proto fvt/proto/kfs_inference_v2.proto -d '{ "model_name": "example-mnist-predictor", "inputs": [{ "name": "inputs", "shape": [1, 784], "datatype": "FP32", "contents": { "fp32_contents": [0.0, 0.0, 1.0, 11.0, 14.0, 15.0, 3.0, 0.0, 0.0, 1.0, 13.0, 16.0, 12.0, 16.0, 8.0, 0.0, 0.0, 8.0, 16.0, 4.0, 6.0, 16.0, 5.0, 0.0, 0.0, 5.0, 15.0, 11.0, 13.0, 14.0, 0.0, 0.0, 0.0, 0.0, 2.0, 12.0, 16.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.0, 16.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0, 7.0, 0.0, 0.0, 0.0, 0.0, 11.0, 13.0, 12.0, 1.0, 0.0] }}]}' localhost:8033 inference.GRPCInferenceService.ModelInfer
```

**Comment by xauthulei** [comment]
@tedhtchang , Thanks, you are right , it should be `inputs` instead of `predict`. 
```
% grpcurl -plaintext -proto fvt/proto/kfs_inference_v2.proto -d '{ "model_name": "example-mnist-predictor", "inputs": [{ "name": "inputs", "shape": [1, 784], "datatype": "FP32", "contents": { "fp32_contents": [0.0, 0.0, 1.0, 11.0, 14.0, 15.0, 3.0, 0.0, 0.0, 1.0, 13.0, 16.0, 12.0, 16.0, 8.0, 0.0, 0.0, 8.0, 16.0, 4.0, 6.0, 16.0, 5.0, 0.0, 0.0, 5.0, 15.0, 11.0, 13.0, 14.0, 0.0, 0.0, 0.0, 0.0, 2.0, 12.0, 16.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.0, 16.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0, 7.0, 0.0, 0.0, 0.0, 0.0, 11.0, 13.0, 12.0, 1.0, 0.0] }}]}' localhost:8033 inference.GRPCInferenceService.ModelInfer

{
  "modelName": "example-mnist-predictor__ksp-c3597b719f",
  "modelVersion": "1",
  "outputs": [
    {
      "name": "classes",
      "datatype": "INT64",
      "shape": [
        "1",
        "1"
      ]
    }
  ],
  "rawOutputContents": [
    "BwAAAAAAAAA="
  ]
}
```

Same time, we need to add this step to doc, right ?

**Comment by tedhtchang** [comment]
@xauthulei Yes thanks. Please add this step. This will help.

**Comment by chinhuang007** [comment]
If we are adding instructions to run predict with the updated predictor, the inputs and outputs probably should be more realistic. There seems to have a mismatch in the sample input, shape is [1, 784] but content is [64]. I don't know how to interpret the outputs either, where shape is ["1", "1"] and rawOutputContents is "BwAAAAAAAAA="

**Comment by ckadner** [comment]
@rafvasq -- this may be a good first issue. Evaluate if there is still a problem, update the doc (or predictor spec) to be consistent with Quickstart, other examples, FVT, ...

**Comment by aartisinghh** [comment]
This is a good first issue for me to contribute in the community. I will work on this now. Thanks

**Comment by rafvasq** [comment]
Thanks @aartisinghh!

**Comment by medinad96** [comment]
I'm happy to help resolve this issue and make doc updates if needed

**Comment by medinad96** [comment]
In testing the documentation steps at [Quickstart](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md#grpc-request) and arriving at the grpcurl request step. I found that both the "name":"inputs" and "predict" options for this grpcurl command are successful as shown in the screenshot below.  This is also documented as “name”:”predict” under the [Predictors docs](https://github.com/kserve/modelmesh-serving/blob/main/docs/predictors/README.md#using-the-deployed-model) :

<img width="1439" alt="Screenshot 2024-03-01 at 2 50 21 PM" src="https://github.com/kserve/modelmesh-serving/assets/24236763/5b4ccdc1-5302-4c75-868f-08d6202e8868">



From reviewing the documentation on the main branch it seems that only "name":"predict" is used.  This issue can be closed since the steps in the documentation no longer cause this issue.

**Comment by rafvasq** [comment]
Thanks for testing and confirming @medinad96.
