### ISSUE TITLE
The etcd connection is incorrect for user namespaces when etcd is configured outside of controller namespace

### ISSUE THREAD

**Issue by chinhuang007** [kserve/modelmesh-serving#186]
**Describe the bug**

If etcd is configured outside of the controller namespace, the generated secret for user namespaces will have an incorrect etcd endpoint.

**To Reproduce**
1. Configure etcd in a separate namespace
2. Deploy modelmesh including a controller namespace, using the etcd created in step 1
3. Enable modelmesh in a user namespace
4. Create a ServingRuntime, which won't work due to the incorrect etcd endpoint 

**Expected behavior**

The generate secret should contain correct etcd endpoints when etcd is in a different namespace from controller.

**Comment by XiangFrank** [comment]
Hi, we found another issue regarding Etcd secret copy. When copying the Etcd secret, seems it would only copy contents in etcd_connection field rather than the whole secret. Is there any reason behind it? Because we're using client_key_file to pass the key in another field, and it was skipped during the copying process.

**Comment by chinhuang007** [comment]
> Is it possible to directly add the namespace information in the Etcd endpoint at the beginning if it is exposed as an internal service? In this case, the extra logic in addData could be removed, and even if users are directly using external IP addresses as the Etcd endpoints it could still be safe.

Thanks for the suggestion. It is what I was thinking as well. Feel free to check out and comment on the work-in-progress patch, https://github.com/kserve/modelmesh-serving/pull/188

**Comment by pvaneck** [comment]
@XiangFrank The `etcd_connection` key in the secret supports other fields like `client_key_file` as shown [here](https://github.com/kserve/modelmesh-serving/blob/main/pkg/mmesh/etcdrangewatcher.go#L32). Is your `client_key_file` being set as a separate key of the secret?
