### ISSUE TITLE
Custom runtime error

### ISSUE THREAD

**Issue by aldwnesx** [kserve/modelmesh-serving#192]
I am trying to port over a custom run time.

I created the ServingRunTime and Predictor following the example on https://github.com/kserve/modelmesh-serving/blob/main/docs/runtimes/custom_runtimes.md

I am getting the following errors

```
modelmesh-serving-custom-runtime-523c6759b1-j2x77   2/4     CrashLoopBackOff   4 (50s ago)   2m35s
```
```
  Warning  Unhealthy  30s                kubelet            Readiness probe failed: Get "http://172.17.0.7:8089/ready": dial tcp 172.17.0.7:8089: connect: connection refused
  Normal   Started    29s (x2 over 34s)  kubelet            Started container puller
  Warning  BackOff    24s                kubelet            Back-off restarting failed container
  Normal   Pulled     13s (x3 over 34s)  kubelet            Container image "kserve/modelmesh-runtime-adapter:v0.8.0" already present on machine
  Normal   Created    13s (x3 over 34s)  kubelet            Created container puller
  Warning  Unhealthy  13s (x6 over 28s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Comment by njhill** [comment]
@aldwnesx you'll need to check the logs of your model server container and possibly the `mm` container. Most likely your container is not coming up properly or not reporting `READY` from its `runtimeStatus` API - the modelmesh container polls/waits for this before it declares itself ready to Kubernetes.

Hopefully the problem should be evident from that but if not feel free to paste some of the log output here.

**Comment by njhill** [comment]
@aldwnesx any update here? can this issue now be closed?

**Comment by ckadner** [comment]
This issue has been stale for more than a year and much of the code has changed since. Feel free to reopen if you can still reproduce this issue in the latest version of [ModelMesh-Serving v0.11.2](https://github.com/kserve/modelmesh-serving/releases/tag/v0.11.2).
