### ISSUE TITLE
Is there a separate Helm chart for ModelMesh?

### ISSUE THREAD

**Issue by OvervCW** [kserve/modelmesh-serving#194]
It seems like ModelMesh can be deployed in combination with KServe from the [KServe Helm chart](https://github.com/kserve/kserve/tree/master/charts/kserve), but is there also a way to deploy only ModelMesh?

We're interested in this because we plan to only use ModelMesh's functionality and not KServe.

**Comment by OvervCW** [comment]
@njhill I don't want to use the install script because it doesn't support release management. All of the other applications we deploy in our cluster do have Helm charts available, which allow us to easily manage them with Terraform.

I've decided to implement my own Helm chart based on the resources that are deployed by the script.

**Comment by njhill** [comment]
> I've decided to implement my own Helm chart based on the resources that are deployed by the script.

@OvervCW great, is that something which you could contribute back to the project?

**Comment by OvervCW** [comment]
@njhill Possibly, yes. It'll depend on our final implementation.

**Comment by ckadner** [comment]
@OvervCW -- Assuming your helm chart conversion went well, would you like to open a PR and contribute them here?

**Comment by OvervCW** [comment]
@ckadner In the end we decided not to use ModelMesh.
