### ISSUE TITLE
Fail to run TensorFlow/Keras MNIST example models in GPU resources

### ISSUE THREAD

**Issue by IntelliJJ824** [kserve/modelmesh-serving#200]
**Describe the bug**

1. GPU serving runtime has been configured by: ~/modelmesh-serving/config/runtimes/triton-2.x.yaml
I have add `nvidia.com/gpu: 1` in both limits and requests fields under the Resources in Yaml file.

2. Reinstall the entire ModelMesh by: `./scripts/install.sh --namespace modelmesh-serving --quickstart`

3. Result: Two Triton pods are successfully assigned Two GPUs, but fail to load the models.
<img width="604" alt="Screenshot 2022-07-28 at 5 58 58 PM" src="https://user-images.githubusercontent.com/27443676/181595539-fe05f9bf-99de-458e-9b69-48d82cabafb4.png">

<img width="591" alt="Screenshot 2022-07-28 at 6 00 37 PM" src="https://user-images.githubusercontent.com/27443676/181595656-ab65b704-fd54-4855-89ce-2e509a8c2265.png">
<img width="747" alt="Screenshot 2022-07-28 at 6 01 12 PM" src="https://user-images.githubusercontent.com/27443676/181595842-985afb1a-fc66-4f0a-b873-eb7d993c9d60.png">

4. Describe the Predictor object for inspection: it shows the error `UNAVAILABLE: Failed to load Model due to Triton runtime error: rpc error: code = Unavailable desc = error reading from server: EOF`

<img width="1440" alt="Screenshot 2022-07-28 at 6 02 50 PM" src="https://user-images.githubusercontent.com/27443676/181596119-f05c9f62-644b-45ac-8f5e-db9a162ae15d.png">

5. Try to start MLServer by using SKLearn, and the TensorFlow model can be successfully loaded. 
<img width="687" alt="Screenshot 2022-07-28 at 6 07 00 PM" src="https://user-images.githubusercontent.com/27443676/181596805-02ce5348-8560-4232-b2ce-fcdf6b7cd739.png">

6. I have tried sent GRPC/CURL inference requests to Triton, but cannot expect a correct response as CPU does. Furthermore, if the SKLearn model is unloaded, the TensorFlow model will show in Fail status as the Step 3 shown.

**Expected behavior**

Two Triton pods are successfully assigned Two GPUs, and successfully load the MNIST example models.

**Environment (please complete the following information):**

- Version 0.8

**Additional context**

The Triton is successfully run, and attach some description information in the Triton-adapter.
<img width="1440" alt="Screenshot 2022-07-28 at 6 15 21 PM" src="https://user-images.githubusercontent.com/27443676/181598163-2c103b19-f191-4cb6-b136-a199f88843b5.png">

Here is the description for the Triton Pods.
<img width="1440" alt="Screenshot 2022-07-28 at 6 18 07 PM" src="https://user-images.githubusercontent.com/27443676/181598687-d89d99ac-e281-4b16-98bb-7d2a48caa810.png">

**Comment by njhill** [comment]
@IntelliJJ824 from the original error it looks likely due to the Triton container restarting, potentially due to OOM. Can see from your `get pods` screenshot that there was a container restart, maybe you could verify that this is the Triton container, and check its logs for clues (use `--previous=true` to see the pre-restart log output).

What you observed with the model later loading is most likely due to model-mesh retrying the load after a few minutes, the fact this happened at the same time as the sklearn model loading I expect was just coincidence.

If it was caused by an OOM it could be related to insufficient mem allocation in the SR spec.

**Comment by IntelliJJ824** [comment]
Hi, yes, when assigning more CPU memory in the Yaml file, it works. This ticket can be safely closed.
