### ISSUE TITLE
Error: Set cross-namespace owner are disallowed

### ISSUE THREAD

**Issue by gaodan-fang** [kserve/modelmesh-serving#211]
**Describe the bug**
The modelmesh controller is trying to set owner reference for resources outside of the current namespace.
```
{"level":"error","ts":1660671661.3458428,"logger":"controller.ServiceReconciler","msg":"Reconciler error","reconciler group":"apps","reconciler kind":"Deployment","name":"wmlserving-controller","namespace":"wo-nba","error":"could not set Service owner reference: cross-namespace owner references are disallowed, owner's namespace argo-wo, obj's namespace wo-nba","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1660671661.352311,"logger":"controller.ServiceReconciler","msg":"Reconciler error","reconciler group":"apps","reconciler kind":"Deployment","name":"router-default","namespace":"openshift-ingress","error":"could not set Service owner reference: cross-namespace owner references are disallowed, owner's namespace argo-wo, obj's namespace openshift-ingress","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
```

**To Reproduce**

Deploy the default model mesh controller and you will see the error in the model mesh controller pod

**Expected behavior**

Should only looking for current name space resources.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

The error went away when i set the [NAMESPACE_SCOPE](https://github.com/kserve/modelmesh-serving/blob/211e052c25c70a82b7df0834433e61cbf620a29c/main.go#L79) to False, so i suspect if this block of code should be `if not r.NamespaceOwned` https://github.com/kserve/modelmesh-serving/blob/b79d771fe43b72cbba1f0fcdf052917761c6ac6a/controllers/service_controller.go#L130-L170

**Comment by njhill** [comment]
@gaodan-fang hopefully this should be addressed by https://github.com/kserve/modelmesh-serving/pull/212.

**Comment by gaodan-fang** [comment]
@njhill thanks for addressing the issue!

**Comment by njhill** [comment]
Closing since this should be fixed per above, @gaodan-fang please feel free to reopen if it's still a problem.
