### ISSUE TITLE
Failed to load Model due to Triton runtime error ？

### ISSUE THREAD

**Issue by melowYX** [kserve/modelmesh-serving#221]
When I tried to load an ONNX model  

{"message":"INTERNAL: Failed to load Model due to Triton runtime error: rpc error: code = Internal desc = failed to load 'example-generator-predictor__ksp-503f133797', no version is available","modelId":"example-generator-predictor__ksp-503f133797","reason":"ModelLoadFailed"}

Why is that?

**Comment by njhill** [comment]
@melowYX please provide your predictor spec and also what your storage file layout looks like.

**Comment by melowYX** [comment]
s3://modelmesh-example-models/
└── demo/config.pbtxt
└── demo/1/model.onnx
└── demo/1/GPT2.onnx.data

kubectl delete -f - <<EOF
apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: example-demo-predictor
spec:
  modelType:
    name: onnx
  path: demo/
  storage:
    s3:
      secretKey: localMinIO
EOF
