### ISSUE TITLE
Question: How to specify a ServingRuntime

### ISSUE THREAD

**Issue by melowYX** [kserve/modelmesh-serving#242]
The ONNX  model was supoorted via ServingRuntime ovms and triton. So when we use kubectl to deploy a onnx model how to specify a ServingRuntime in a .yaml file

**Comment by njhill** [comment]
@melowYX you probably found this but you can either:
- Reference the runtime explicitly by name in the Predictor/InferenceService (`runtime` field)
- Set the `autoSelect` field in the `supportedModelFormat` lists of the ServingRuntime specs to true for the one(s) that you want to use for a particular model type (onnx in this case)
