### ISSUE TITLE
Kustomize versions between latest release and main quick start guides

### ISSUE THREAD

**Issue by rafvasq** [kserve/modelmesh-serving#243]
An inconsistency in the main branch's Quick Start Guide seems a bit confusing:

[The guide](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md) notes that kustomize v3.2.0+ is supported, but the first step asks the user to checkout the latest release (0.9) which doesn't include #233 and only supports kustomize v4.0.0+, although that's correctly communicated on [the release branch](https://github.com/kserve/modelmesh-serving/blob/release-0.9/docs/quickstart.md) itself. 

This could cause some confusion for new users or developers landing on the main branch, especially those coming from Kubeflow which requires kustomize 3.2.0.

**Comment by ckadner** [comment]
Thank you Rafel. This is a bit of a conundrum. Users hitting the Quickstart guide will naturally land on the `latest` documentation that show **kustomize v3.2+** yet the 0.9 release they are asked to clone does not have the corresponding script changes to support kustomize 3.2.

I supposed we want to revert the doc change so the Quickstart shows required kustomzie v4.0+ again and create an issue on the 1.0 release milestone/project to make sure we update the Quickstart again when we draw the 1.0 release.

@njhill ?
