### ISSUE TITLE
"code":3,"message":"json: cannot unmarshal string into Go value of type main.RESTRequest"

### ISSUE THREAD

**Issue by MLHafizur** [kserve/modelmesh-serving#255]
Getting `{"code":3,"message":"json: cannot unmarshal string into Go value of type main.RESTRequest"}` which sending an inference request. Codes:

```
from mlserver.codecs.pandas import PandasCodec # required mlserver>=1.1.0, 
payloads = "./IDA_en.ndjson"
df = pd.read_json(payloads, lines=True)
df = df.fillna('')
payload = PandasCodec.encode_request(df, use_bytes=False)
response = requests.post("http://localhost:8008/v2/models/muc-en-aa-predictor/infer", json=payload.json())
```

I never experienced the error. What's the wrong?

**Comment by njhill** [comment]
@MLHafizur could you share the output of `print(payload.json())`

**Comment by MLHafizur** [comment]
@njhill here is input sample:

`{"id": null, "parameters": null, "inputs": [{"name": "TF_Idf_score", "shape": [1], "datatype": "FP64", "parameters": null, "data": [10.5184540149]}, {"name": "bm25", "shape": [1], "datatype": "FP64", "parameters": null, "data": [1.5876147942]}, {"name": "deduplication", "shape": [1], "datatype": "BYTES", "parameters": null, "data": [["No Duplicates"]]}, {"name": "deduplications", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["No Duplicates"]}, {"name": "description", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["Oct 21, 2021 \u2014 Mihoko Matsubara is Chief Cybersecurity Strategist, NTT Corporation, Tokyo, being responsible for cybersecurity thought leadership."]}, {"name": "duplicate_content", "shape": [1], "datatype": "INT64", "parameters": null, "data": [0]}, {"name": "duplicates", "shape": [1], "datatype": "BYTES", "parameters": null, "data": [[0]]}, {"name": "duplicates_message", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["No similar records "]}, {"name": "excluded", "shape": [1], "datatype": "INT64", "parameters": null, "data": [0]}, {"name": "excluded_keyword_content", "shape": [1], "datatype": "BYTES", "parameters": null, "data": [""]}, {"name": "flag_original_record", "shape": [1], "datatype": "INT64", "parameters": null, "data": [1]}, {"name": "full_name_match", "shape": [1], "datatype": "INT64", "parameters": null, "data": [0]}, {"name": "full_text", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["A Singapore Government Agency Website Show menu Advisory Panels and Committees Cyber Security Advisory Panel Decrease font size Increase ………………responsible for cybersecurity thought leadership. Cyber Security Advisory Panel   Monetary Authority of Singapore"]}, {"name": "fuzzy_name_match", "shape": [1], "datatype": "INT64", "parameters": null, "data": [100]}, {"name": "id", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["1d418c48-ef31-4833-9d28-d165eb963c6c"]}, {"name": "jurisdiction", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["Global"]}, {"name": "language", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["en"]}, {"name": "language_id", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["en"]}, {"name": "model_preds", "shape": [1], "datatype": "FP64", "parameters": null, "data": [0.11637508120000001]}, {"name": "record_number", "shape": [1], "datatype": "INT64", "parameters": null, "data": [0]}, {"name": "score", "shape": [1], "datatype": "FP64", "parameters": null, "data": [5.4941331513]}, {"name": "scores_1", "shape": [1], "datatype": "FP64", "parameters": null, "data": [0.0022134821]}, {"name": "source_name", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["www.mas.gov.sg"]}, {"name": "source_type", "shape": [1], "datatype": "BYTES", "parameters": null, "data": [[]]}, {"name": "text", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["A Singapore Government Agency …….. updated on 21 Oct 2021"]}, {"name": "tfidf_cossim", "shape": [1], "datatype": "FP64", "parameters": null, "data": [0.3594798194]}, {"name": "title", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["Cyber Security Advisory Panel - Monetary Authority of Singapore"]}, {"name": "unique_query_fields_count", "shape": [1], "datatype": "INT64", "parameters": null, "data": [0]}, {"name": "url", "shape": [1], "datatype": "BYTES", "parameters": null, "data": ["https://www.mas.gov.sg/who-we-are/MAS-Advisory-Panels-and-Committees/Cyber-Security-Advisory-Panel"]}], "outputs": null}`

**Comment by MLHafizur** [comment]
@njhill any help please?

**Comment by MLHafizur** [comment]
Hey @njhill The issue is gone, if we use `json=payloads.dict()` instead of` json=payloads.json()` in  `requests.post()`.
But getting another error and concern: if we use `json=payloads.dict()` it is going through the runtime codes. 

```
async def predict(self, payloads: InferenceRequest) -> InferenceResponse:   
        df = self._extract_inputs(payloads)
```

```
def _extract_inputs(self, payloads: InferenceRequest) -> pd.DataFrame:
        input = pd.DataFrame()
        for inp in payloads.inputs:
            print("Framing")
            if inp.name == "TF_Idf_score":
                input[inp.name] = inp.data
       return input

```

The error is: 
```
<class 'mlserver.types.dataplane.InferenceRequest'>
Data Encoding Done
Sending Request
{"code":3,**"message":"illegal base64 data at input byte 8"**}
```
I checked the custom runtime mlserver container logs, it seems like _extract_inputs() function is returning an empty dataframe.
I debugged the function issue in a different test script  it seems like that:

```
  for inp in payloads.inputs:
            print("Framing")
            if inp.name == "TF_Idf_score":
                input[inp.name] = inp.data

```
`payloads.inputs` is giving the following error:

`AttributeError: 'str' object has no attribute 'dict'`

which is very logical because` payloads.dict()` is returning a `str`. But `payloads.inputs` is behaving good with Pandas Codec payloads which type is `<class 'mlserver.types.dataplane.InferenceRequest'>`.

On the other hand, python's `requests.post()` is not allowing ` 'mlserver.types.dataplane.InferenceRequest'` as paylaod.

What can I do in this case?

**Comment by MLHafizur** [comment]
@njhill Looking forward to hear from you.

**Comment by MLHafizur** [comment]
The error is coming  from, I think 
```
 response = requests.post(
    "http://localhost:8008/v2/models/muc-en-aa-predictor/infer", 
    json=payloads.dict()
    )
```
I am not getting any other clues unfortunately. But seems like it is not going through the` predict() ` function of the custom run. It supposed to  print many logs.

 Something else in between the client code and the model runtime seems to be raising the error.

**Comment by MLHafizur** [comment]
Today again getting `{"code":3,"message":"json: cannot unmarshal string into Go struct field RESTRequest.inputs of type uint8"}` error with same payload and codes.

**Comment by njhill** [comment]
@MLHafizur this error is coming from the REST proxy which transcodes from the KServe V2 REST protocol to equivalent gRPC requests for routing through modelmesh.

Unfortunately, `BYTES` type tensors where the data is string-encoded aren't currently supported, see https://github.com/kserve/rest-proxy/issues/8. Hopefully we can add support for that soon.

**Comment by MLHafizur** [comment]
Hey @njhill Thanks for your response. What are the other ways I can follow?

**Comment by MLHafizur** [comment]
Hey @njhill , unfortunately nothing is working with my text data:` sentences = list(df['full_text'].values)` I have tried all of the ways proposed in MLServer Codec to encode my text data (list of sentences) .  I am frustrated now, Can you please tell me how may I make it work?

**Comment by njhill** [comment]
@MLHafizur you could send it as a gRPC request instead, not sure if the MLServer Codecs include any support for that. If not you could convert the payload manually to protobuf.

**Comment by MLHafizur** [comment]
@njhill we are planning not to user gRPC, Our preference is REST.

**Comment by njhill** [comment]
@MLHafizur FYI support for this has now been merged.
