### ISSUE TITLE
modemesh metrics is not getting exported

### ISSUE THREAD

**Issue by Agarwal-Saurabh** [kserve/modelmesh-serving#281]
modemesh metrics is not getting exported

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/23380740/201721464-1565dc4c-c2ee-438c-88ae-965335f3ba92.png">

`{"instant":{"epochSecond":1668423238,"nanoOfSecond":750799948},"thread":"prom-http-thread-0","level":"ERROR","loggerName":"com.ibm.watson.prometheus.NettyServer","message":"Prometheus HTTP(S) server processing failure","thrown":{"commonElementCount":0,"localizedMessage":"javax.net.ssl.SSLHandshakeException: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN","message":"javax.net.ssl.SSLHandshakeException: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN","name":"io.netty.handler.codec.DecoderException","cause":{"commonElementCount":15,"localizedMessage":"error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN","message":"error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN","name":"javax.net.ssl.SSLHandshakeException","extendedStackTrace":[{"class":"io.netty.handler.ssl.ReferenceCountedOpenSslEngine","method":"shutdownWithError","file":"ReferenceCountedOpenSslEngine.java","line":1074,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.ReferenceCountedOpenSslEngine","method":"sslReadErrorResult","file":"ReferenceCountedOpenSslEngine.java","line":1365,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.ReferenceCountedOpenSslEngine","method":"unwrap","file":"ReferenceCountedOpenSslEngine.java","line":1305,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.ReferenceCountedOpenSslEngine","method":"unwrap","file":"ReferenceCountedOpenSslEngine.java","line":1392,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.ReferenceCountedOpenSslEngine","method":"unwrap","file":"ReferenceCountedOpenSslEngine.java","line":1435,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.SslHandler$SslEngineType$1","method":"unwrap","file":"SslHandler.java","line":221,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.SslHandler","method":"unwrap","file":"SslHandler.java","line":1342,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.SslHandler","method":"decodeJdkCompatible","file":"SslHandler.java","line":1235,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.ssl.SslHandler","method":"decode","file":"SslHandler.java","line":1284,"exact":false,"location":"netty-handler-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.codec.ByteToMessageDecoder","method":"decodeRemovalReentryProtection","file":"ByteToMessageDecoder.java","line":510,"exact":false,"location":"netty-codec-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.codec.ByteToMessageDecoder","method":"callDecode","file":"ByteToMessageDecoder.java","line":449,"exact":false,"location":"netty-codec-4.1.77.Final.jar","version":"4.1.77.Final"}]},"extendedStackTrace":[{"class":"io.netty.handler.codec.ByteToMessageDecoder","method":"callDecode","file":"ByteToMessageDecoder.java","line":480,"exact":false,"location":"netty-codec-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.handler.codec.ByteToMessageDecoder","method":"channelRead","file":"ByteToMessageDecoder.java","line":279,"exact":false,"location":"netty-codec-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":379,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":365,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"fireChannelRead","file":"AbstractChannelHandlerContext.java","line":357,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.DefaultChannelPipeline$HeadContext","method":"channelRead","file":"DefaultChannelPipeline.java","line":1410,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":379,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":365,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.DefaultChannelPipeline","method":"fireChannelRead","file":"DefaultChannelPipeline.java","line":919,"exact":false,"location":"netty-transport-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe","method":"epollInReady","file":"AbstractEpollStreamChannel.java","line":800,"exact":false,"location":"netty-transport-classes-epoll-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.epoll.EpollEventLoop","method":"processReady","file":"EpollEventLoop.java","line":487,"exact":false,"location":"netty-transport-classes-epoll-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.channel.epoll.EpollEventLoop","method":"run","file":"EpollEventLoop.java","line":385,"exact":false,"location":"netty-transport-classes-epoll-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.util.concurrent.SingleThreadEventExecutor$4","method":"run","file":"SingleThreadEventExecutor.java","line":995,"exact":false,"location":"netty-common-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.util.internal.ThreadExecutorMap$2","method":"run","file":"ThreadExecutorMap.java","line":74,"exact":false,"location":"netty-common-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","file":"FastThreadLocalRunnable.java","line":30,"exact":false,"location":"netty-common-4.1.77.Final.jar","version":"4.1.77.Final"},{"class":"java.lang.Thread","method":"run","file":"Thread.java","line":833,"exact":false,"location":"?","version":"?"}]},"endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","contextMap":{},"threadId":42,"threadPriority":5}
`
modelmesh release 0.9
kserve 0.9

@njhill

**Comment by Agarwal-Saurabh** [comment]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/23380740/201703648-28559714-455a-42b6-b087-d438f28a32c5.png">
also cluster IP not coming for modemesh service

**Comment by tjohnson31415** [comment]
Hello @Agarwal-Saurabh.

For the Cluster IP question:
By default, modelmesh component exposes a [headless Kube service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) to support client-side gRPC load balancing. This improves load distribution and throughput, so it is recommended to use it in this configuration. You can have your install use a non-headless service by changing the `headlessService` config to false ([see the configuration docs](https://github.com/kserve/modelmesh-serving/blob/main/docs/configuration/README.md)).

---

For the metrics issues, I'm trying to understand better what your set up is. There is an `SSLV3_ALERT_CERTIFICATE_UNKNOWN` error in the stack trace, which means you are running with TLS?

Does the screenshot show an attempt to connect with a browser the metrics port on one of the modelmesh pods? I don't see any port in the URL, so I am a little confused by that. As a simpler check, can you try port-forwarding to one of the modelmesh containers pods at the metrics port and just use `curl` or some other simple http client?

**Comment by Agarwal-Saurabh** [comment]
hello @tjohnson31415 
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/23380740/201721331-4a6a8191-55e3-4a2a-b9a7-744c7862f9ec.png">
here is the port-forwarding method. I posted a wrong screenshot earlier

**Comment by tjohnson31415** [comment]
@Agarwal-Saurabh Were you able to get this working with the information above?

**Comment by Agarwal-Saurabh** [comment]
Yes thanks a lot !!

**Comment by anhquan075** [comment]
Hi, I have an issue related to the Prometheus port 2112 when trying to integrate with Signoz. I followed to the [docs](https://signoz.io/docs/userguide/send-metrics/#enable-a-prometheus-receiver) and set a job to scrape metrics from the modelmesh-serving prometheus metrics like this:
```
prometheus:
  config:
    scrape_configs:
      - job_name: "modelmesh-serving-collector"
        scrape_interval: 30s
        static_configs:
          - targets:
              [
                "modelmesh-serving.modelmesh-serving.svc.cluster.local:2112",
              ]
        scheme: http
        enable_http2: false
```
But I got the error in the `otel-colellector-metrics` pod below:
```
2023-10-20T11:01:37.646Z	debug	scrape/scrape.go:1353	Scrape failed	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_pool": "modelmesh-serving-collector", "target": "http://modelmesh-serving.modelmesh-serving.svc.cluster.local:2112/metrics", "error": "Get \"http://modelmesh-serving.modelmesh-serving.svc.cluster.local:2112/metrics\": EOF"}
```
Any ideas to solve that issue ? @tjohnson31415. Thank you
