### ISSUE TITLE
Add Dockerfile for `modelmesh-minio-dev-examples` image

### ISSUE THREAD

**Issue by rafvasq** [kserve/modelmesh-serving#302]
Similar to #297, this issue focuses on the `Dockerfile` for the [`modelmesh-minio-dev-examples` image](https://hub.docker.com/r/kserve/modelmesh-minio-dev-examples/tags). 

This [image is used](https://github.com/kserve/modelmesh-serving/blob/main/config/dependencies/fvt.yaml#L109) when deploying the ModelMesh Serving [with the FVT option](https://github.com/kserve/modelmesh-serving/blob/main/scripts/install.sh#L262-L265) and contains a set of models needed for running FVTs.

---

**UPDATE 2/1/2023:** We now have the [kserve/modelmesh-minio-examples](https://github.com/kserve/modelmesh-minio-examples) repository dedicated to maintain and build the ModelMesh MinIO Examples Docker image(s):

- https://github.com/kserve/modelmesh-minio-examples/blob/v0.10.0/Dockerfile#L45 (FVT build)

**Comment by ckadner** [comment]
We now have the [kserve/modelmesh-minio-examples](https://github.com/kserve/modelmesh-minio-examples) repository dedicated to maintain and build the ModelMesh MinIO Examples Docker image(s):

- https://github.com/kserve/modelmesh-minio-examples/blob/v0.10.0/Dockerfile#L45 (FVT build)
