### ISSUE TITLE
Pre-built grafana dashboard for modelmesh metrics

### ISSUE THREAD

**Issue by njhill** [kserve/modelmesh-serving#335]
There is a grafana dashboard we developed for displaying the various prometheus metrics exposed by modelmesh in a clear/useful manner.

However, it was created originally for "standalone" modelmesh use where there's only a single runtime / Deployment per logical modelmesh service. This means it should work well as-is with modelmesh-serving in cases where only one runtime is used, but needs to be tested and probably adjusted/generalized for multi-runtime use.

Potential issues include the fact that the available memory is assumed to be a single pool available to any model, but with multiple runtimes it could in reality be effectively partitions.

Here is the current exported dashboard json: [ModelMeshMetricsDashboard.json.gz](https://github.com/kserve/modelmesh-serving/files/10839643/ModelMeshMetricsDashboard.json.gz)

**Comment by rafvasq** [comment]
@njhill I'm wondering where the one we have in the [`modelmesh-performance` repo](https://github.com/kserve/modelmesh-performance/tree/main/docs/monitoring) fits in to this. It includes some views like [resource usage per runtime container](https://github.com/kserve/modelmesh-performance/blob/main/docs/images/grafana_dashboard_modelmesh_example_1.jpg). Would the resulting dashboard perhaps be a combination of the one you shared and the `modelmesh-performance` one?

**Comment by njhill** [comment]
@rafvasq this one is more comprehensive and I think should include most of what's in the other one. If there's anything important in the other one which isn't in this one then it can be added. I am not a fan of the big dials that show current values - they are nice for demos but I don't think very useful in practice.
