### ISSUE TITLE
Memory leak - OOMKilled

### ISSUE THREAD

**Issue by Kokkini** [kserve/modelmesh-serving#351]
**Describe the bug**
The mm container in the pod has a memory leak. The memory usage of mm container never decreases.

**To Reproduce**
I used ModelMesh load 6 images processing models (classification + segmentation) using Triton server with GPU (replicas=2). I sent 10k requests (512x512 images) to these models and the memory consumption of mm container increased very fast then never went down. All requests were successful. This is a picture of the increase. The memory stayed constant at 1.9GB after that without any decrease.
<img width="726" alt="Screen Shot 2023-03-27 at 1 53 54 PM" src="https://user-images.githubusercontent.com/22306485/228400217-bb102677-3fd2-4c75-83de-94a5255abbe5.png">

Even when I sent small number of requests (200 requests), the memory increased then stayed there without decreasing.
<img width="688" alt="Screen Shot 2023-03-28 at 5 47 18 PM" src="https://user-images.githubusercontent.com/22306485/228400538-42c63ee0-03a1-4702-b796-39d2942a04dd.png">

**Expected behavior**

The memory of mm container increases while processing the requests and then decreases to a low value after it finishes.

**Environment (please complete the following information):**
Running modelmesh-serving version 0.10.0 on AWS EKS.

2 instances of Triton server version 22.07 on T4 GPU.

**Comment by tjohnson31415** [comment]
Hello @Kokkini. Thanks for including the graphs and details in the issue!

The memory profile shown is not too surprising to me as the ModelMesh container is running a Java process. I'm no Java expert, but my understanding is that it will do its own memory heap management inside the container and will typically not release memory back to the operating system until it hits its own limits.

> The memory of mm container increases while processing the requests and then decreases to a low value after it finishes.

Without changes to the JVM launch configuration in the ModelMesh container, I wouldn't expect to see a decrease until it is pushing up against the memory limits it was configured with.

---

I see the title mentions "OOMKilled" but the issue body mentions that "All requests were successful". Can you please clarify if you were able to get the container to crash by sending requests.

Also, am I reading it correctly that the memory requests and limits are set to different values in your deployment? If so, that may be why it ends up crashing. The ModelMesh container configures its internal Java memory management based on what it can read from the `/sys/fs/cgroup` in the container (see all of the memory related code in the boot script starting [here](https://github.com/kserve/modelmesh/blob/d1d01564af5bb5e472789ad856b09a73072f1b85/src/main/scripts/start.sh#L311)). I believe that the value it reads from `/sys/fs/cgroup/memory/memory.limit_in_bytes` is set by the Kubernetes limits. Setting requests less than limits can then result in the JVM being told it can use more memory than it should.

**Comment by Kokkini** [comment]
@tjohnson31415 Thank you for the very quick and detailed reply. 

The container crashed with OOMKilled when I sent lots of requests. "All requests were successful" only applies when the memory hadn't reached the limit. Sorry for the confusion. 

When I set memory limit = request, OOMKilled still happened. The mm container crashed and come back with a lower memory usage (image below). I also noticed that after crashing, mm container doesn't free all of the memory it occupied and still has very high memory usage (image below). I think after the container restart, the memory level should be as low as the first part of the graph. Do you know what causes this behavior and how to fix?

<img width="702" alt="Screen Shot 2023-03-29 at 9 41 16 AM" src="https://user-images.githubusercontent.com/22306485/228610588-1acddd96-da48-40e6-8ed6-f8893062a6a2.png">

**Comment by tjohnson31415** [comment]
Thanks for clarifying about the restarts.

> I think that after the container restart, the memory level should be as low as the first part of the graph (about 0.2GB). Do you know what may cause this behavior and how to fix?

That's a head scratcher 🤔. I also expect that it would drop all the way down. May be worth double checking that the memory metrics being recorded in the graphs match what you'd expect and are only measuring the `mm` container. You are setting memory requests and limits to 2Gi just for the `mm` container?

The memory usage in the `mm` container for large request like these should mostly be just due to pushing the requests through to Triton. To support retrying failed requests, I think MM does hold the request in memory though. Do you have an estimate for how many requests are in-flight concurrently?

I'm also curious if you hit anything like what was reported in https://github.com/kserve/modelmesh-serving/issues/286 with a "OutOfDirectMemoryError" logged by `mm`. Did you have to apply any memory related configurations other than just increasing the memory requests/limits?

Also, if you could upload the full logs from the `mm` container for one of its crashes, I can look through it and see if anything stands out to me.

**Comment by Kokkini** [comment]
@tjohnson31415 
Updates: 
The problem turned out to be: 10k requests at the same time were too much. They didn't fit into 2GB memory. 

I tried spreading out the 10k requests in a longer time period (10 minutes instead of 1 minute) and observed that the memory worked correctly. It increased gradually until near the limit then plateaued without any OOMKilled.

About the "not releasing memory after restart" issue, it actually released the memory. However, I was sending a lot of requests, thus the memory dropped after restarting and increased back to full so fast that the graph did not catch it (the granularity of the graph was 1 minute).

I increased the memory to 4GB and now it works fine with 10k requests. Thank you for your support.

The issue can be safely closed.

**Comment by WaterKnight1998** [comment]
How did you manage GPU memory in the end @Kokkini ? I saw [here](https://github.com/kserve/modelmesh/issues/82#issuecomment-1582028690) that you should use: `CONTAINER_MEM_REQ_BYTES` configured to VRAM and `MODELSIZE_MULTIPLIER` to compute how many VRAM is going to use based on file size.

**Comment by Kokkini** [comment]
@WaterKnight1998 I couldn't manage GPU memory. I just calculate the number of models that will fit into the VRAM (about 40 in my case), check the model size on disk then set the CONTAINER_MEMORY_REQ_BYTES and MODELSIZE_MULTIPLIER so that: 
`CONTAINER_MEMORY_REQ_BYTES / (MODELSIZE_MULTIPLIER * model_size_on_disk) = 40`
