### ISSUE TITLE
InferenceService scale to zero

### ISSUE THREAD

**Issue by andreapairon** [kserve/modelmesh-serving#388]
Hi, is it possibile to dynamically unload an `InferenceService` (so a ML model) from a `ServingRuntime` if no traffic is received?
Basically to unload the GPU when there are no incoming requests for a specific `InferenceService` and then reload it on the GPU when requests start arriving again.

I don't know if it's the right place to look into, but from this page https://kserve.github.io/website/0.10/modelserving/autoscaling/autoscaling/#create-inferenceservice seems that the `InferenceService` CRD can scale automatically to zero by setting `minReplicas: 0` under `spec.predictor` in the YAML definition.

Is it possible? If so, do we need KNative to enable the zero-scaling behaviour or the standalone KServe ModelMesh Serving is enough?

Thanks in advance

**Comment by ckadner** [comment]
@andreapairon -- did you already take a look at question/issue #353 ?

**Comment by andreapairon** [comment]
@ckadner just saw. Yeah, my question is basically the same as the issue you linked
