### ISSUE TITLE
Data Plane API Error - "Not Found" when Retrieving Model Metadata

### ISSUE THREAD

**Issue by anhquan075** [kserve/modelmesh-serving#418]
**Describe the bug**

When I try to use the [Kserve Data Plane API](https://kserve.github.io/website/0.10/reference/swagger-ui/) in ModelMesh Serving to get the model metadata, an error with the code **5** and message **"Not Found"** is encountered. 
```
{"code":5, "message":"Not Found"}
```

**To Reproduce**
1. Deploy a `isvc`
2. Port forward the `modelmesh-serving` service and send request to the route `v2/models/${MODEL_NAME}[/versions/${MODEL_VERSION}]` 

**Expected behavior**

The expected behavior is to receive a response similar to Kserve in [here](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata-response-json-object) with the following format:
```
$metadata_model_response =
{
  "name" : $string,
  "versions" : [ $string, ... ] #optional,
  "platform" : $string,
  "inputs" : [ $metadata_tensor, ... ],
  "outputs" : [ $metadata_tensor, ... ]
}
```
**Screenshots**
I created a example isvc using the mnist model
<img width="726" alt="image" src="https://github.com/kserve/modelmesh-serving/assets/54442768/666924c6-cde8-4140-a037-b77995e4f9df">
Upon sending a request to the route `/v2/models/${MODEL_ID}` (`/v2/models/mnist-isvc`), I received the following error message:<img width="585" alt="image" src="https://github.com/kserve/modelmesh-serving/assets/54442768/49151bbb-724e-4a03-a6ab-20f1ef761e5f">

**Environment (please complete the following information):**

- OS: MacOS Monterey 12.6

**Additional context**
Are there any guides or suggestions available to help resolve this issue? My task requires retrieving model metadata such as input/output names and shapes.

**Comment by njhill** [comment]
This needs to be added to the rest-proxy, see https://github.com/kserve/rest-proxy/issues/14
