### ISSUE TITLE
Update Go to supported version (1.20)

### ISSUE THREAD

**Issue by Jooho** [kserve/modelmesh-serving#452]
Currently work is in progress to upgrade all Golang based ModelMesh repos to Go version 1.19:

- kserve/modelmesh-serving#379 (modelmesh-serving)
- kserve/modelmesh-runtime-adapter#68
- kserve/rest-proxy#28

Based on this table of supported Go versions: https://endoflife.date/go ; Go 1.19 is no longer supported (since Aug 2023) and Go version 1.20 is expected to no longer be supported by 2Q 2024.

We should update all Go based repos to use use Go version 1.21.

**Comment by ckadner** [comment]
I see [ubi8/go-toolset:1.20](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?image=6548a49c277c59213791c4f7) has been made available on 11/15/2023

And [ubi9/go-toolset:1.20](https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?image=654d1e78f6be4e847240a8b5) has been made available on 11/9/2023

So we could try upgrading to Go 1.20 for ModelMesh-Serving release v0.12
