### ISSUE TITLE
ModelMesh performance benchmarks

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#5]
Would be good to analyze the performance and perhaps compare with the other current model serving methods available.

Some ideas:

- Maximum number of models able to deploy on a specific cluster. Density testing.
- Request latency under varying loads or model densities (using both gRPC and REST when supported)

Other ideas and tooling for benchmarking are welcome.

**Comment by tedhtchang** [comment]
We will use this [benchmark guide](https://github.com/kubeflow/kfserving/blob/master/docs/samples/multimodelserving/benchmark/BENCHMARK.md) as a reference

**Comment by tedhtchang** [comment]
I am thinking to use the test result in [benchmark guide](https://github.com/kubeflow/kfserving/blob/master/docs/samples/multimodelserving/benchmark/BENCHMARK.md) as the baseline for the ModelMesh performance test. To do that, I will need some information on how the test was done particularly the tools used to run the tests and the cluster specs. Based the guide there are 2 types of tests.
1. Density (Stress)
- 6 workers clusters(spec?): measure how many models can be packed into the cluster
- model: simple string
- Tools:
  - driver?
  - logging?
  - monitoring?
  - reporting?

2. Latency (Performance)
- CPU: deploy 5 string models, send REST/gRPC, measure latency
- GPU: deploy 5 BERT models?, send REST/gRPC, measure latency
- Tools
  - driver: 
    - Vegeta: Since the modelmesh service has gRPC endpoint so we may use [Trunks](https://github.com/straightdave/trunks) instead.
    - logging?
    - monitoring?
    - reporting?

**Comment by pvaneck** [comment]
A lot of work has been done on the performance side. There is now a nightly performance test being run. Related scripts/config/docs can be found here: https://github.com/kserve/modelmesh-performance
