### ISSUE TITLE
Remove TrainedModel CR reconciliation

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#51]
With the TrainedModel CRD being deprecated in favor of using the InferenceService CRD for both single model and multi model deployments, we can go ahead and remove support for TrainedModel reconciliation. Our current support is still using the old `serving.kubeflow.org/v1alpha1`  APIGroupVersion anyway.

**Comment by pugangxa** [comment]
/assign
I can help on this issue.
