### ISSUE TITLE
gRPC example in the quick start guide is yields an error

### ISSUE THREAD

**Issue by crobby** [kserve/modelmesh-serving#67]
While running through the quick start guide, I get an error when trying to run the gRPC example under the "perform an inference test" section.

Running the command as written in the guide gives an error:  
```
MODEL_NAME=example-mnist-predictor
grpcurl \
  -plaintext \
  -proto fvt/proto/kfs_inference_v2.proto \
  -d '{ "model_name": "'"${MODEL_NAME}"'", "inputs": [{ "name": "predict", "shape": [1, 64], "datatype": "FP32", "contents": { "fp32_contents": [0.0, 0.0, 1.0, 11.0, 14.0, 15.0, 3.0, 0.0, 0.0, 1.0, 13.0, 16.0, 12.0, 16.0, 8.0, 0.0, 0.0, 8.0, 16.0, 4.0, 6.0, 16.0, 5.0, 0.0, 0.0, 5.0, 15.0, 11.0, 13.0, 14.0, 0.0, 0.0, 0.0, 0.0, 2.0, 12.0, 16.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.0, 16.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0, 7.0, 0.0, 0.0, 0.0, 0.0, 11.0, 13.0, 12.0, 1.0, 0.0] }}]}' \
  localhost:8033 \
  inference.GRPCInferenceService.ModelInfer
```

**To Reproduce**

1. Install via the quick start guide instructions
2. Try to do an inference with the sample given for gRPC
3. See the following error
```
Failed to process proto source files.: could not parse given files: open fvt/proto/kfs_inference_v2.proto: no such file or directory
```
**Expected behavior**
I expect the inference to be returned as documented.

Client Version: 4.5.0-202005291417-9933eb9
Server Version: 4.9.0-rc.5
Kubernetes Version: v1.22.0-rc.0+8719299

When I run the REST example, I *do* get the expected results for the inference.

**Comment by SebastianScherer88** [comment]
@crobby 's solution worked for me, too - thanks!
