### ISSUE TITLE
Import ServingRuntime and InferenceService types from KServe

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#99]
Types for these resources are currently defined in two places: the `kserve` repository and the `modelmesh-serving` repository. Let's investigate importing these types from KServe and using those within modelmesh-serving as a step towards unification.

**Comment by yuzisun** [comment]
I have updated the KServe `go.mod` you should be able to import the types now.

**Comment by pvaneck** [comment]
Closed via #140 and https://github.com/kserve/modelmesh-serving/pull/146
